name: Dist

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false

    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    env:
      GITHUB_ACTION_REPO: ${{ github.action_repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix profile install nixpkgs#git nixpkgs#nodejs
      - name: Build TypeScript using npm
        run: |
          npm install
          npm run bundle

      - name: Copy metadata from source
        run: cp action.yaml dist
      - name: Push the "dist" branch
        working-directory: ./dist
        run: |
          git init
          git checkout -b dist
          git add -A .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "dist" --allow-empty
          git remote add origin "https://inclyc:$GITHUB_TOKEN@github.com/inclyc/nixf-tidy-action.git"
          git push --force origin dist
